# Generated by Django 4.0.4 on 2022-05-10 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='yourWebSite',
            field=models.URLField(),
        ),
    ]
