# Generated by Django 4.0.4 on 2022-06-21 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_alter_contact_yourwebsite'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='yourEmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='contact',
            old_name='fullName',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='yourWebSite',
        ),
        migrations.AddField(
            model_name='contact',
            name='phone',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='contact',
            name='subject',
            field=models.CharField(max_length=300),
        ),
    ]
