# Generated by Django 4.0.4 on 2022-05-10 14:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=70, unique=True, validators=[django.core.validators.MaxLengthValidator(100), django.core.validators.MinLengthValidator(2)], verbose_name='Title'),
        ),
    ]
