# Generated by Django 4.0.4 on 2022-05-13 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('one_to_many', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article1',
            options={'verbose_name': 'Articlee', 'verbose_name_plural': 'Articless'},
        ),
        migrations.AlterModelOptions(
            name='author1',
            options={'verbose_name': 'Authorss', 'verbose_name_plural': 'Authorss'},
        ),
        migrations.AlterModelTable(
            name='article1',
            table='articless',
        ),
        migrations.AlterModelTable(
            name='author1',
            table='authorss',
        ),
    ]
