# Generated by Django 4.0.4 on 2022-06-22 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='category',
            field=models.CharField(choices=[('Debt', ((11, 'Credit Card'), (12, 'Student Loans'), (13, 'Taxes'))), ('Entertainment', ((21, 'Books'), (22, 'Games'))), ('Everyday', ((31, 'Groceries'), (32, 'Restaurants')))], default=1, max_length=80),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='expiration_date',
            field=models.DateField(null=True),
        ),
    ]
