# Generated by Django 4.0.4 on 2022-06-22 12:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactApp', '0002_contact_category_contact_expiration_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='expiration_date',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
